from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import load
import os

class OpenPsarcConan(ConanFile):
    name = "open-psarc"
    license = "MIT"
    author = "TNT Coders <tnt-coders@googlegroups.com>"
    url = "https://github.com/tnt-coders/open-psarc"
    description = "PSARC archive reader"
    topics = ("psarc", "archive", "compression")
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "build_cli": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
        "build_cli": True,
    }
    exports_sources = "CMakeLists.txt", "src/*", "include/*", "cli/*", "cmake-package-builder/*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def requirements(self):
        self.requires("zlib/1.3.1")
        self.requires("xz_utils/5.8.1")
        self.requires("openssl/3.6.0")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["BUILD_CLI"] = self.options.build_cli
        tc.generate()

        deps = CMakeDeps(self)
        deps.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        # Use CMake's own package config files generated by cmake-package-builder
        self.cpp_info.set_property("cmake_find_mode", "config")
        self.cpp_info.set_property("cmake_file_name", "OpenPSARC")
        self.cpp_info.set_property("cmake_target_name", "OpenPSARC::OpenPSARC")
